_BASE_: "Base-RandBox.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 81
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (30000,)
  MAX_ITER: 35000
TEST:
  EVAL_PERIOD: 35000
  PREV_INTRODUCED_CLS: 20
  CUR_INTRODUCED_CLS: 20
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
