_BASE_: "Base-RandBox.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  RandBox:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 81
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (70000, 75000, 77000)
  MAX_ITER: 80000
TEST:
  EVAL_PERIOD: 80000
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
